### ISSUE TITLE
Why no releases?

### ISSUE THREAD

**Issue by mubed** [Nylle/StyleCop.Console#2]
Are there no releases for this tool, so that I can use them without having to compile it myself?

**Comment by Nylle** [comment]
Hi mubed, assuming you are using StyleCop to analyse C# code I was under the impression you are able to compile C# code as well. Doubleclick the sln-file, hit Ctrl+F5 and voilà you have your build. Pretty easy, huh? Additionally, at the time of the release there was no free C# build service available. 
However, TravisCI does support C# now so I added a build (see the shiny badge). I will look into publishing tags back to GitHub. Cheers, Jan

**Comment by mubed** [comment]
Thank you for the description. I need runnable versioned releases to be tested on our CI server configuration and then be linked to in the documentation. Having no releases on GitHub, we have to version and archive the releases ourselves.

Another (maybe a bit off-topic) question: Is it possible to configure the tool to use newer StyleCop dlls?

**Comment by Nylle** [comment]
I'm working on a way to publish releases from Travis back to GitHub. If you want a newer StyleCop-Version you're welcome to make a pull-request.

**Comment by mubed** [comment]
I didn't mean to update the StyleCop binaries inside your project, but having a way to configure StyleCop.Console at runtime to reference StyleCop from an external source. This way, I'll be able to use any StyleCop version.
To achieve this, you need to reference StyleCop DLLs dynamically and make it customizable using a config file.

**Comment by Nylle** [comment]
Why me? It's your requirement, so why don't you do it yourself and make a pull-request? This is open source.

**Comment by Nylle** [comment]
Releases are now available.
